#Hugo configuration
title = "New Project"
baseURL = "https:\/\/jpchang.com\/jpchang"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758991"
subfolder = "\/jpchang"
firstpartycookies = true
cookiedomain = "jpchang.com"
